<?php
$paths=array(
	"function/function.php",
        "../common/common/function.php",
	"libs/core/DB.class.php",
	"libs/core/VIEW.class.php",
	"libs/db/mysql.class.php",
	"libs/view/smarty/Smarty.class.php",	
	"libs/memcache/memcache.class.php"
);